jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build the app
      run: ./gradlew build
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Enable KVM group perms
      run: 'echo ''KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"''
        | sudo tee /etc/udev/rules.d/99-kvm4all.rules

        sudo udevadm control --reload-rules

        sudo udevadm trigger --name-match=kvm

        '
    - continue-on-error: true
      name: Tests
      uses: reactivecircus/android-emulator-runner@6b0df4b0efb23bb0ec63d881db79aefbc976e4b2
      with:
        api-level: 31
        arch: x86_64
        disable-animations: true
        disk-size: 8G
        emulator-options: -memory 4096 -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        heap-size: 512M
        profile: pixel_3a
        ram-size: 4096M
        script: 'mkdir -p artifacts/report

          adb logcat -c

          adb logcat -G 16M && adb logcat -g

          ./gradlew connectedCheck || touch tests_failing

          adb logcat -d > artifacts/logcat.txt

          cp -r app/build/reports/androidTests/connected/* artifacts/report/

          if adb shell ''[ -e /sdcard/Pictures/screenshots ]''; then adb pull /sdcard/Pictures/screenshots
          artifacts/; fi

          test ! -f tests_failing

          '
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: instrumented-test-report
        path: 'artifacts/*

          '
name: build
on:
  repository_dispatch:
    types: trigger-ga___build-app-workflow.yaml
